# Generated by Django 5.1.3 on 2024-12-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_bankrupt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrupt',
            name='account',
        ),
    ]
